[phases.setup]
nixPkgs = ["go_1_21", "postgresql"]

[phases.install]
cmds = [
  "export GOPATH=/root/go",
  "export PATH=$GOPATH/bin:$PATH",
  "go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest",
  "ls -la $GOPATH/bin/migrate || echo 'migrate binary not found'"
]

[phases.build]
cmds = [
  "cd backend && go build -o bin/server cmd/server/main.go"
]

[start]
cmd = "cd backend && ./bin/server"
