[phases.setup]
# Install Go runtime for building the app, PostgreSQL client for psql (optional), and curl for downloading migrate binary
nixPkgs = ["go_1_21", "postgresql", "curl"]

# No pre-install commands needed; migrate binary will be downloaded at release time by scripts/migrate.sh
[phases.install]
cmds = []

[phases.build]
cmds = [
  "cd backend && go build -o bin/server cmd/server/main.go"
]

[start]
cmd = "cd backend && ./bin/server"
