ALTER TABLE programs ALTER COLUMN title DROP NOT NULL;
ALTER TABLE programs ALTER COLUMN title DROP DEFAULT;

ALTER TABLE programs ALTER COLUMN description DROP NOT NULL;
ALTER TABLE programs ALTER COLUMN description DROP DEFAULT;
